RedHatInsights/kerlescan

kerlescan/view_helpers.py
The view_helpers.py method ensure_has_permissions() needs to hand RBACDenied exception so it can raise HTTPError for forbidden status.
=> More RBAC permissions support

kerlescan/audit_logging.py
Use it as `logger.audit("message")`
to see output as `[2021-02-18 15:29:43 +0000] [29] [AUDIT] message`.
=> DRFT-131 Adds AUDIT log level to app logger

kerlescan/audit_logging.py
=> DRFT-245 Fixes handling of auth_key is None

kerlescan/constants.py
=> [DRFT-22] Add cpu_model fact to drift

kerlescan/constants.py
=> Add new svc endpoints to constants for notifications

kerlescan/config.py, kerlescan/constants.py
=> [DRFT-252] Adds config and constants for notification feature

kerlescan/view_helpers.py
=> Allows auth_key to be None

kerlescan/constants.py
=> Add endpoint for short_circuit comparison

kerlescan/constants.py
=> Removes leading slash from query template

kerlescan/constants.py
=> Update internal baseline endpoint

kerlescan/service_interface.py
=> Handles 401 the same way as 403

kerlescan/view_helpers.py
=> Adds simple audit log for shared secret check

Pipfile, Pipfile.lock
=> [DRFT-352] Update to Python 3.8

kerlescan/constants.py, kerlescan/profile_parser.py, tests/test_info_parser.py
=> [DRFT-162] Expose gpg_pubkeys in system_profile

kerlescan/profile_parser.py
=> Fix reversed indices for gpg_pubkeys

kerlescan/constants.py, kerlescan/exceptions.py, kerlescan/service_interface.py, tests/test_service_interface.py
=> [DRFT-310] Allows fetch_url to accept HTTP method parameter

kerlescan/constants.py, kerlescan/system_baseline_service_interface.py, tests/test_system_baseline_service_interface.py
=> [DRFT-310] Adds endpoint for deleting system in baseline service

.pre-commit-config.yaml, .travis.yml, Pipfile, Pipfile.lock, README.md, kerlescan/audit_logging.py, kerlescan/cloudwatch.py, kerlescan/config.py, kerlescan/constants.py, kerlescan/hsp_service_interface.py, kerlescan/inventory_service_interface.py, kerlescan/metrics_registry.py, kerlescan/paginate.py, kerlescan/profile_parser.py, kerlescan/rbac_service_interface.py, kerlescan/service_interface.py, kerlescan/system_baseline_service_interface.py, kerlescan/view_helpers.py, pyproject.toml, setup.py, tests/test_info_parser.py, tests/test_rbac.py, tests/test_service_interface.py, tests/test_system_baseline_service_interface.py
Changes include:
- Pre-Commit config files
- README changes to include pre-commit info
Signed-off-by: Fellipe Henrique <fpedrosa@redhat.com>
=> [DRFT-623] kerlescan commit hooks

kerlescan/view_helpers.py, tests/test_rbac.py
=> [DRFT-627] Fix case where multiple permissions required

kerlescan/view_helpers.py
Needed to reset a flag within a loop.
=> Fix notifications rbac

kerlescan/profile_parser.py, tests/test_info_parser.py
=> Remove gpg-pubkey

Pipfile, Pipfile.lock, kerlescan/config.py
=> Kerlscan changes to run Drift Backend in Clowder

kerlescan/config.py
=> Changed drift-backend clowder's hostname

kerlescan/config.py
=> [DRFT-492] Fix historical-system-profiles hostname settings for Clowder

kerlescan/system_baseline_service_interface.py
=> Adds internal auth header to delete systems from notifications

kerlescan/constants.py, kerlescan/system_baseline_service_interface.py, tests/test_system_baseline_service_interface.py
=> Corrects system baseline systems delete endpoint parameters

kerlescan/view_helpers.py
=> [DRFT-310] Corrects order of auth checks

kerlescan/view_helpers.py
=> Corrects case of missing auth key

kerlescan/constants.py
=> [DRFT-310] Uses path params not query params with internal systems endpoint

kerlescan/constants.py
First, need to merge https://github.com/RedHatInsights/kerlescan/pull/58
=> [DRFT-507] Expose MSSQL system facts in Drift

Pipfile, Pipfile.lock, kerlescan/unleash.py
=> [DRFT-763] Setup Unleash to use feature flags

kerlescan/unleash.py
=> Fix unleash url bug

kerlescan/unleash.py
=> [DRFT-763] Add missing bearer keyword in token

kerlescan/cloudwatch.py
=> Fix isClowderEnabled method call

kerlescan/inventory_service_interface.py
=> [DRFT-1019] Add stale_warning_timestamp to system profile

kerlescan/profile_parser.py, tests/test_info_parser.py
=> [DRFT-1088] Handles None value in system tags

kerlescan/view_helpers.py
=> Adds org-id related methods and updates log messages

.pre-commit-config.yaml
=> Updates pre-commit deps

kerlescan/inventory_service_interface.py
Making Inventory API call multi-threaded
=> [EVNT-783] Refactor Inventory API call

kerlescan/cloudwatch.py
- Updates cloudwatch call with new watchtower and boto3
=> Changes watchtower call to accomodate updated deps

.pre-commit-config.yaml
=> Updates pre-commit to python3

kerlescan/view_helpers.py
- Uses **kwarsg with most view_helpers
- Adds openapi_url check to ensure account and org_id checks
- Clears some kwargs uses in view_helpers.py
=> Adds openapi_url check to ensure account and org_id checks

.github/workflows/ci-dev-tests.yml
=> Updates poetry to 1.5.0

kerlescan/constants.py
=> feat(DRFT-1361): Add systemd fact to drift

kerlescan/rbac_service_interface.py, setup.cfg, tests/test_rbac.py
- Adds assertion to permission test
- Mocks fetch_url response instead of get_perms in RBAC test
- Adds parser for RBAC's inventory group ids
=> ESSNTL-4821 inventory groups

kerlescan/rbac_service_interface.py, tests/test_rbac.py
=> Handles missing resourceDefinitions in RBAC response

kerlescan/profile_parser.py
=> fix(RHINENG-1497): parse object facts values to string

kerlescan/cloudwatch.py
=> feat: cloudwatch for more loggers

kerlescan/rbac_service_interface.py, kerlescan/view_helpers.py
- Adds inventory to list of application to RBAC call
- Cleans up some comments
=> ESSNTL 4821 inventory groups application in rbac call

kerlescan/rbac_service_interface.py, tests/test_rbac.py
=> fix: proper storing of rbac_filters to passed on object

kerlescan/rbac_service_interface.py, kerlescan/view_helpers.py, tests/test_rbac.py
=> feat: changes format of return value for RBAC filters

kerlescan/constants.py, kerlescan/service_interface.py, kerlescan/system_baseline_service_interface.py
ESSNTL-5248
- feat: allow fetch_url to accept json and pass it to requests
- feat: adds method to update Baselines' associated systems
- fix: allow more before hooks to check for internal drift request
- feat: stops requiring identity type "System"
=> ESSNTL 5248 baselines internal update mapped systems endpoint

.github/workflows/ci-dev-tests.yml
[RHINENG-1716] Updates poetry to 1.6
=> chore: updates poetry to 1.6

kerlescan/constants.py, kerlescan/inventory_service_interface.py
=> feat: filters out centos systems

kerlescan/inventory_service_interface.py
=> fix: Fixes correct selector for operating_system

kerlescan/view_helpers.py
Adding service account support into `ensure_entitled` method.
=> feat:(RHINENG-6114): Adding Service Account support

kerlescan/unleash.py
=> fix(unleash): Remove legacy Unleash Auth. header

kerlescan/audit_logging.py, kerlescan/cloudwatch.py, kerlescan/profile_parser.py, kerlescan/service_interface.py, kerlescan/view_helpers.py
Logging changes I've made so far are to reflect the following levels:
Debug - `Detailed information, typically only of interest to a developer trying to diagnose a problem.`
Info - `Confirmation that things are working as expected.`
Warning - `An indication that something unexpected happened, or that a problem might occur in the near future (e.g. ‘disk space low’). The software is still working as expected.`
Error - `Due to a more serious problem, the software has not been able to perform some function.`
The custom log level `Audit` has not been touched, still waiting for a decision from App SRE. 
=> feat(RHINENG-7984): implement logging best pracices
